version: '3'

silent: true

tasks:
  default: ${GOTASK_BIN:-task} --list

  run:
    desc: Run the binary for the current platform
    cmds:
      - go run main.go {{.CLI_ARGS}}

  build:
    desc: Build the binary for the current platform
    cmds:
      - go build -o bin/cloudflare-dynamic-dns main.go

  goreleaser:build:
    desc: Build binaries for all platforms using goreleaser
    cmds:
      - goreleaser build --snapshot --rm-dist
